[package]
name = "testauskalkki"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "tkl"
path = "src/main.rs"

[lib]
name = "libtestauskalkki"
path = "src/lib/lib.rs"

[dependencies]
num = "0.4"
